//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsDeviceParameterIdentifier {
  XDPI_Unknown = 0x0000,
  XDPI_PacketErrorRate = 0x0001,
  XDPI_ExtendedBuffer = 0x0002,
  XDPI_UplinkTimeout = 0x0003,
  XDPI_SyncLossTimeout = 0x0004
}

}
