//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsIccCommand {
  XIC_StartRepMotion = 0x00,
  XIC_StopRepMotion = 0x01,
  XIC_StoreResults = 0x02,
  XIC_RepMotionState = 0x03
}

}
