//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XDA {

public enum XsOption {
  XSO_None = 0,
  XSO_Calibrate = 0x0001,
  XSO_Orientation = 0x0002,
  XSO_KeepLastLiveData = 0x0004,
  XSO_RetainLiveData = 0x0008,
  XSO_RetainBufferedData = 0x0010,
  XSO_OrientationInLiveStream = 0x0020,
  XSO_OrientationInBufferedStream = 0x0040,
  XSO_RetainRecordingData = XSO_RetainBufferedData,
  XSO_OrientationInRecordingStream = XSO_OrientationInBufferedStream,
  XSO_ApplyOrientationResetToCalData = 0x0080,
  XSO_Reserved = 0x8000,
  XSO_All = 0x807F
}

}
